apiVersion: v1
kind: Service
metadata:
  name: distance-calculator-service
spec:
  selector:
    app: distance-calculator
  ports:
    - protocol: TCP
      port: 80  # Port you want to expose the service on
      targetPort: 8080  # Port your application listens on in the pods
  type: ClusterIP  # You can change the service type as needed
