apiVersion: apps/v1
kind: Deployment
metadata:
  name: distance-calculator
spec:
  replicas: 1  # Number of desired pods
  selector:
    matchLabels:
      app: distance-calculator
  template:
    metadata:
      labels:
        app: distance-calculator
    spec:
      containers:
      - name: distance-calculator-container
        image: quay.io/coder_bhai/distance_calculator:latest
        ports:
        - containerPort: 8080  # Port your application listens on
