apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: distance-calculator-service
spec:
  to:
    kind: Service
    name: distance-calculator-service
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge
