apiVersion: apps/v1
kind: Deployment
metadata:
  name: distance-calculator
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: distance-calculator
  template:
    metadata:
      labels:
        app: distance-calculator
    spec:
      containers:
      - name: distance-calculator
        image: {{ .Values.distanceCalculator.image }}
        env:
        - name: KAFKA_CLIENT_ID
          value: {{ .Values.receiver.environment.KAFKA_CLIENT_ID }}
        - name: KAFKA_BROKERS
          value: {{ .Values.receiver.environment.KAFKA_BROKERS }}
        - name: KAFKA_TOPIC
          value: {{ .Values.receiver.environment.KAFKA_TOPIC }}
        - name: GRPC_HOST
          value: {{ .Values.storer.GRPC_HOST }}
        - name: GRPC_PORT
          value: "{{ .Values.storer.GRPC_PORT }}"

---
apiVersion: v1
kind: Service
metadata:
  name: distance-calculator
spec:
  selector:
    app: distance-calculator
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 80 

