apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: receiver
spec:
  to:
    kind: Service
    name: receiver
    weight: 100
  port:
    targetPort: 8080
  websocket: true  # Enable WebSocket support