apiVersion: apps/v1
kind: Deployment
metadata:
  name: storer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storer
  template:
    metadata:
      labels:
        app: storer
    spec:
      containers:
      - name: storer
        image: quay.io/coder_bhai/storer
        env:
          - name: DATABASE_URL
            value: postgresql://postgres:mypassword@postgresql:5432/openshiftdb
          - name: GRPC_HOST
            value: storer
          - name: GRPC_PORT
            value: "50051"
        ports:
        - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: storer
spec:
  selector:
    app: storer
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
