apiVersion: apps/v1
kind: Deployment
metadata:
  name: storer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storer
  template:
    metadata:
      labels:
        app: storer
    spec:
      containers:
      - name: storer
        image: {{ .Values.storer.image }}
        env:
          - name: DATABASE_URL
            value: {{ .Values.postgres.URL }}
          - name: GRPC_HOST
            value: {{ .Values.storer.GRPC_HOST }}
          - name: GRPC_PORT
            value: "{{ .Values.storer.GRPC_PORT }}"
        ports:
        - containerPort: {{ .Values.storer.GRPC_PORT }}

---
apiVersion: v1
kind: Service
metadata:
  name: storer
spec:
  selector:
    app: storer
  ports:
    - protocol: TCP
      port: {{ .Values.storer.GRPC_PORT }}
      targetPort: {{ .Values.storer.GRPC_PORT }}
